inveniosoftware/invenio-deposit

CHANGES.rst, RELEASE-NOTES.rst, invenio_deposit/version.py
=> Invenio-Deposit v0.1.0

invenio_deposit/validation_utils.py, tests/test_deposit_validators.py
* FIX Fixes MintedDOIValidator, so that it correctly checks if DOI was
already minted for the specific upload. (addresses zenodo/zenodo#285)
Signed-off-by: Adrian Pawel Baran <adrian.pawel.baran@cern.ch>
=> deposit: MintedDOIValidator fix

setup.py, tests/test_deposit_validators.py
=> global: import and dependency fixes

invenio_deposit/autocomplete_utils.py, setup.py
* FIX Adds missing dependency to invenio-knowledge package and fixes
imports.
=> installation: invenio-knowledge>=0.1.0

.travis.yml, invenio_deposit/storage.py, invenio_deposit/tasks.py
* INCOMPATIBLE Removes bibdocfile module.
(addresses inveniosoftware/invenio#3233)
=> global: removal of bibdocfile

invenio_deposit/form.py, invenio_deposit/templates/deposit/run_group_start_base.html
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> deposit: panel icon support

setup.py
=> installation: bump of min version of dependencies

CHANGES.rst, RELEASE-NOTES.rst, invenio_deposit/version.py, requirements-docs.txt
=> Invenio-Deposit v0.2.0

setup.py
=> installation: optional invenio-jsonschema>=0.1.0

invenio_deposit/tasks.py
=> tasks: removal of HstRECORD modification check

.travis.yml, MANIFEST.in
Fixes the current issue with building bundles when getting `invenio-deposit` from PyPi.
=> installation: less inclusion in MANIFEST.in

invenio_deposit/acl.py, invenio_deposit/autocomplete_utils.py, invenio_deposit/bundles.py, invenio_deposit/field_widgets.py, invenio_deposit/fields/jsonfield.py, invenio_deposit/filter_utils.py, invenio_deposit/models.py, invenio_deposit/processor_utils.py, invenio_deposit/restful.py, invenio_deposit/storage.py, invenio_deposit/tasks.py, invenio_deposit/views/deposit.py, requirements-devel.txt, setup.py, tests/helpers.py, tests/test_deposit_models.py, tests/test_type_simplerecord.py
=> global : fix invenio_utils imports

invenio_deposit/api.py, invenio_deposit/config.py, invenio_deposit/providers.py, requirements-devel.txt, setup.py, tests/conftest.py, tests/test_api.py
=> tests: addition of test cases for API

examples/app.py, invenio_deposit/api.py, invenio_deposit/config.py, setup.py, tests/conftest.py
=> config: configurable JSON schema defaults

invenio_deposit/api.py, invenio_deposit/views/rest.py, tests/conftest.py, tests/test_views_rest_files.py
=> api: database files iterator

.travis.yml, invenio_deposit/api.py, invenio_deposit/search.py, setup.py, tests/conftest.py
=> api: automatic indexing

.travis.yml, invenio_deposit/api.py, invenio_deposit/config.py, invenio_deposit/links.py, invenio_deposit/views/rest.py, setup.py, tests/test_views_rest.py
=> tests: simple REST workflow

invenio_deposit/static/js/invenio_deposit/app.js, invenio_deposit/templates/invenio_deposit/edit.html
=> global: typos fix

invenio_deposit/config.py, invenio_deposit/templates/invenio_deposit/edit.html
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> config: typo fixation

invenio_deposit/api.py, invenio_deposit/utils.py, tests/conftest.py
- Renames key files to _files.
- It gives us some time before moving the implementation to Invenio-Records-Files.
=> api: suport for bucket snapshot

invenio_deposit/api.py, invenio_deposit/serializers.py, invenio_deposit/views/rest.py, setup.py
=> global: usage of invenio-records-files

invenio_deposit/utils.py
=> global: fix scope check

invenio_deposit/config.py, invenio_deposit/templates/invenio_deposit/index.html
* Adds configuration for search facets.
=> global: deposit search facets

invenio_deposit/api.py, invenio_deposit/jsonschemas/deposits/deposit-v1.0.0.json, invenio_deposit/mappings/deposits/deposit-v1.0.0.json, run-tests.sh, tests/test_views_rest_files.py
* Updated JSON schema
* Populates created_by field on deposit creation.
=> schema update and created_by population

invenio_deposit/api.py, tests/test_api.py
=> api: protection of update and clear methods

invenio_deposit/errors.py, invenio_deposit/views/rest.py, requirements-devel.txt, setup.py, tests/conftest.py, tests/helpers.py, tests/test_views_rest.py, tests/test_views_rest_files.py
=> views: fix files REST API and zenodo testsuite porting

requirements-devel.txt, setup.py
This reverts commit 172a17ef055f92967dfd22c606d89f22cf482120.
--
cc @lnielsen
=> Revert "installation: pinned invenio-records-files 1.0.0a2"

invenio_deposit/api.py, invenio_deposit/errors.py, setup.py, tests/conftest.py, tests/helpers.py, tests/test_api.py, tests/test_views_rest.py
* Adds record merging. (closes #61)
=> api: record merging addition

invenio_deposit/api.py, invenio_deposit/errors.py, setup.py, tests/conftest.py, tests/helpers.py, tests/test_api.py, tests/test_views_rest.py
=> api: prevent bucket creation on publish

docs/conf.py, invenio_deposit/static/templates/invenio_deposit/selectstatus.html, invenio_deposit/templates/invenio_deposit/index.html, setup.py
* Fixes issue with active facet not being highlighted.
=> templates: facets display fix

invenio_deposit/api.py
* Refactors the Deposit.publish method.
=> api: refactoring of publish method

invenio_deposit/views/rest.py
* Indexes published record after record have been committed to the
database.
=> views: index record on publishing

invenio_deposit/api.py
* NEW Adds the possibility to override the default PID fetcher
and minter in Deposit subclasses. (closes #80)
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> api: overridable deposit fetcher and minter

invenio_deposit/config.py, invenio_deposit/ext.py, invenio_deposit/receivers.py, invenio_deposit/signals.py, invenio_deposit/views/rest.py
* Adds post_action signal to REST actions.
=> global: addition of post_action signal in REST

.travis.yml, CHANGES.rst, RELEASE-NOTES.rst, invenio_deposit/version.py, invenio_deposit/views/rest.py
=> release: v1.0.0a1

invenio_deposit/templates/invenio_deposit/edit.html
=> templates: fix jinja format

invenio_deposit/version.py
=> version: post-release bump

invenio_deposit/api.py
* Adds support for customizing file processing during deposit
publishing.
=> api: process files customization

CHANGES.rst, RELEASE-NOTES.rst, invenio_deposit/version.py
=> release: v1.0.0a2

invenio_deposit/translations/en/LC_MESSAGES/messages.po, invenio_deposit/translations/messages.pot
=> translations: initial message catalog

invenio_deposit/config.py
=> config: usage of {} instead dict()

invenio_deposit/bundles.py
=> bundles: invenio-records-js v0.0.3

invenio_deposit/jsonschemas/deposits/deposit-v1.0.0.json
=> global: extra descriptions to deposit metadata

invenio_deposit/config.py, invenio_deposit/links.py, tests/test_views_rest.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> links: addition of ``html`` key

CHANGES.rst, RELEASE-NOTES.rst, invenio_deposit/version.py
=> release: v1.0.0a6

invenio_deposit/api.py, invenio_deposit/ext.py, invenio_deposit/links.py, tests/test_api.py
* Fix discard action in order to to avoid last record published
changes.
=> api: fix discard action, default deposit endpoints prefixes

.gitignore, .travis.yml, MANIFEST.in, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/requirements.txt, examples/static/templates/app/deposit.html, setup.py, tests/conftest.py, tests/test_examples_app.py
* Adds test_example_app.py. (closes #118)
=> tests: addition of test_example_app.py

.gitignore, .travis.yml, MANIFEST.in, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/requirements.txt, examples/static/templates/app/deposit.html, invenio_deposit/views/rest.py, run-tests.sh, setup.py, tests/conftest.py, tests/test_examples_app.py
=> setup: isort glob fix

.gitignore, .travis.yml, MANIFEST.in, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/requirements.txt, examples/static/templates/app/deposit.html, invenio_deposit/bundles.py, invenio_deposit/views/rest.py, run-tests.sh, setup.py, tests/conftest.py, tests/test_examples_app.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> bundles: invenio-records-js version bump

invenio_deposit/config.py, invenio_deposit/ext.py, invenio_deposit/templates/invenio_deposit/edit.html, invenio_deposit/views/ui.py, tests/test_invenio_deposit.py
* Enhances deposit views to allow different deposit types to use
different jsonchemas and schemaforms. (closes #108)
=> views: multiple deposits per site

invenio_deposit/views/rest.py, tests/test_views_rest.py
=> views: fix action result

CHANGES.rst, RELEASE-NOTES.rst, invenio_deposit/version.py
Signed-off-by: Ioannis Tsanaktsidis ioannis.tsanaktsidis@cern.ch
=> release: v1.0.0a7

CHANGES.rst, RELEASE-NOTES.rst, invenio_deposit/links.py, invenio_deposit/version.py
=> release: v1.0.0a8

invenio_deposit/links.py
=> links: automatically extracted actions

examples/app-teardown.sh
* FIX Fixes rm calls in app-teardown.sh (closes #148).
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> examples: app-teardown.sh's rm calls fix

.travis.yml, invenio_deposit/api.py, setup.py, tests/conftest.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> api: signals connected to an app
